practice/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name = 'login'),
    path('sign-up/', views.sign_up, name = 'signup'),
    path('logout', views.logout_view, name = 'logout')
]

practice/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_page, name = 'page'),
    path('create/', views.article_create, name = 'create'),
    path('<slug>/', views.article_detail, name = 'details')
]

practice/practice/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('', views.home)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

practice/accounts/models.py
from django.db import models

# Create your models here.

practice/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100) 
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumb = models.ImageField(default = 'default.png', blank = True)
    author = models.ForeignKey(User, on_delete =  models.CASCADE, default = None)

    def __str__(self):
        return self.title
    
    def snippet(self):
        if len(self.body) <= 32: 
            return self.body
        else:
            return self.body[:32] + "..."

practice/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = [
            'title',
            'body',
            'slug',
            'thumb'
        ]

practice/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:page')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:page')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/sign_up.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:page')

practice/articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_page(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_page.html', {'articles': articles})

def article_detail(request, slug):
    article = Article.objects.get(slug = slug)
    return render(request, 'articles/article_detail.html', { 'article': article})

@login_required(login_url = '/accounts/login')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('articles:page')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

practice/practice/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    # return HttpResponse('homepage')
    return render(request, 'home.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

practice/accounts/templates/accounts/account_page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title> Account </title>
    </head>
    
    <body>
        <h1> Sign Up </h1>
        <h1> Log In </h1>
    </body>
</html>

practice/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1> Login </h1>

    <form action="{% url 'accounts:login' %}" class="site-form" method = 'POST'>
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name = 'next' value = "{{request.GET.next}}" >
        {% endif %}
        <input type="submit" value = "Login">
    </form>

{% endblock %}

practice/accounts/templates/accounts/sign_up.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1> Sign Up </h1>

    <form action="{% url 'accounts:signup' %}" class="site-form" method = 'POST'>
        {% csrf_token %}
        {{ form }}
        <input type="submit" value = "Signup">
    </form>

{% endblock %}

practice/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

    <div class="create-article">
        <h2> Create an Article here </h2>

        <form action="{% url 'articles:create' %}" method = 'post' class = 'site-form' enctype= "multipart/form-data">
            {% csrf_token %}
            {{ form }}

            <input type="submit" value = 'Create'>
        </form>
    </div>

{% endblock %}

practice/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="article">
        <div class="article-detail">
            <img src= "{{ article.thumb.url }}" alt="" class="thumb"/>
            <h1> {{ article.title }} </h1>
            <p> {{ article.body }} </p>
            <p> {{ article.date }} </p>

        </div>

    </div> 

{% endblock %}

practice/articles/templates/articles/article_page.html
{% extends 'base_layout.html' %}

{% block content %}

    <div class = 'articles'> 
        {% for article in articles %}
            <div class="article"> 

                <h2> <a href = "{% url 'articles:details' slug=article.slug %}"> {{ article.title }} </a> </h2>
                <p> {{ article.snippet }} </p>
                <p> {{ article.date }} </p>
                <p> {{ article.author.username }} </p>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}

practice/templates/about.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <title> About Us</title>
    </head>
    
    <body>
        <h1> This is the about page </h1>
    </body>

</html>

practice/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel = "stylesheet" href = "{% static 'styles.css' %}">

        <title>Article</title>
    </head>

    <body>
        <header class="wrapper">
            <h1> <a href= "{% url 'articles:page' %}" class="logo"> Article </a> </h1>

            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <form action="{% url 'accounts:logout' %}" class = 'logout-view' method = 'post'>
                                {% csrf_token %}
                                <button type = 'submit'> Logout </button>
                            </form>
                        </li>
                        <li> <a href="{% url 'articles:create' %}" class = 'article-prompt'> Create An Article </a> </li>
                        <li class="name"> Welcome {{ user }} </li>
                    {% else %}
                        <li> <a href="{% url 'accounts:signup' %}"> Sign Up </a> </li>
                        <li> <a href="{% url 'accounts:login' %}"> Login </a> </li>   
                    {% endif %}
                </ul>
            </nav>
        </header>
        
       <div class="wrapper"> 
            
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

practice/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title> Homepage </title>
    </head>

    <body>
        <h1> This is my homepage </h1>
        <p> Homepage of the website </p>
    </body>
</html>